# Generated by Django 4.1.1 on 2022-10-03 14:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('core_location', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('year_created', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('controls', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('year_created', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('desc', models.TextField(blank=True)),
                ('game_location', models.FileField(upload_to='')),
                ('count_played', models.IntegerField(default=0)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameservice.platform')),
            ],
        ),
    ]
