# Generated by Django 4.1.1 on 2022-10-17 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('core_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('core_path', models.TextField()),
                ('config_file', models.FileField(upload_to='static/core/config')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('genre_name', models.CharField(max_length=255)),
                ('background', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PopularGame',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('game_name', models.CharField(max_length=255)),
                ('cover', models.FileField(upload_to='static/images/platform/popular_games/cover/')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('console_logo', models.FileField(upload_to='static/images/platform/console_logo/')),
                ('console_preview', models.FileField(upload_to='static/images/platform/console_preview/')),
                ('controls', models.FileField(upload_to='static/images/platform/controls/')),
                ('game_box', models.FileField(upload_to='static/images/platform/game_box/')),
                ('year_created', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('description', models.TextField()),
                ('music', models.FileField(upload_to='static/music/platform/')),
                ('popular_games', models.ManyToManyField(to='gameservice.populargame')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('year_created', models.IntegerField()),
                ('nb_played', models.IntegerField()),
                ('favorite', models.BooleanField(default=False)),
                ('cover', models.FileField(upload_to='static/game/cover/')),
                ('config', models.FileField(null=True, upload_to='static/game/config')),
                ('nb_player', models.IntegerField(default=1)),
                ('trailer_url', models.URLField()),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameservice.core')),
                ('genres', models.ManyToManyField(to='gameservice.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameservice.platform')),
            ],
        ),
    ]
