# Generated by Django 4.1.1 on 2022-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservice', '0002_alter_core_config_file_alter_game_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game',
            field=models.FileField(null=True, upload_to='static/game/games'),
        ),
    ]
