#!/bin/bash
flatpak run org.mozilla.firefox --kiosk http://localhost:8006/ &
PID=$!
echo $PID
END=50
x=$END
while [ $x -gt 0 ]; 
do 
  xdotool search "Mozilla Firefox" windowmove %@ 800 0
  x=$(($x-1))
  sleep 1
done
wait $PID
