# Generated by Django 4.1.1 on 2023-01-15 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hologram',
            fields=[
                ('holo_uuid', models.UUIDField(default=uuid.UUID('64fe0529-4d21-42e1-9338-6223e4115eee'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('holo_url', models.URLField()),
            ],
        ),
    ]
